### ISSUE TITLE
Async Storage for QuestionState

### ISSUE THREAD

**Issue by ethen001** [CodeletApp/codelet-app#36]
## Background

- We need the data in our app to persist after the app is put in the background or closed. Currently the state is cleaned after app is put inthe background.
## Tasks

- [x] install Async Storage in the app
- [x] fit async storage into our flux architecture for global state management
## User Story
Ex: The user has to put background the app in the to send a text message but the user is currrently working on step 2 of the question.
- User should be able to return the app and return the app and continue working

- [ ] data is persisted when app is closed or put in background
- [ ] architecture changes made to `QuestionState`
## Due Date

Janirary 15, 2020
