### ISSUE TITLE
Profile Basic Page is needed

### ISSUE THREAD

**Issue by Maker-Mark** [CodeletApp/codelet-app#56]
## Background

We want a basic profile for people to be able to view
## Tasks
- [x] Make basic profile layout with: 
     - [x] Profile header
     - [x] Rating box 
     - [x] History

## Acceptance Criteria

- [x] Has grading on three criteria (approach, implementation, and analysis)
- [x] Has "History" of recent problems

## User Story
Ex: As a user in step 2 of a question I want to:
-  View my profile, including after I complete a question

## Due Date
2/5/20
