### ISSUE TITLE
Design Algo Enhancements

### ISSUE THREAD

**Issue by Maker-Mark** [CodeletApp/codelet-app#59]
## Background

The current look in designing the Algo is below standard
## Tasks

- [ ] Clean up the blue tag to be smooth with the card
- [ ] Make Your solution scrollable and go down as far as one needs to see the full option.
- [ ] Highlight "selected" algo to convey what's selected
- [ ] Backend: Category field for filtering

## User Story
The look and feel of all pages feels consistent
